<?xml version="1.0" encoding="utf-8"?>
<Database Name="zsgl_solution" Class="FilesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=STC-PC\SQL2005;Initial Catalog=zsgl_solution;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="zsgl_solutionConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.wjgl_files" Member="wjgl_files">
    <Type Name="wjgl_files">
      <Column Name="file_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="file_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="file_bz" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="file_path" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="file_scsj" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="floder_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>