#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4961
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="zsgl_solution")]
	public partial class LsbhDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertlsgl_lsbh(lsgl_lsbh instance);
    partial void Updatelsgl_lsbh(lsgl_lsbh instance);
    partial void Deletelsgl_lsbh(lsgl_lsbh instance);
    #endregion
		
		public LsbhDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["zsgl_solutionConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LsbhDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LsbhDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LsbhDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LsbhDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<lsgl_lsbh> lsgl_lsbh
		{
			get
			{
				return this.GetTable<lsgl_lsbh>();
			}
		}
	}
	
	[Table(Name="dbo.lsgl_lsbh")]
	public partial class lsgl_lsbh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _lsbh_id;
		
		private string _lsbh_name;
		
		private string _lsbh_beforetime;
		
		private string _lsbh_lasttime;
		
		private string _lsbh_code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlsbh_idChanging(int value);
    partial void Onlsbh_idChanged();
    partial void Onlsbh_nameChanging(string value);
    partial void Onlsbh_nameChanged();
    partial void Onlsbh_beforetimeChanging(string value);
    partial void Onlsbh_beforetimeChanged();
    partial void Onlsbh_lasttimeChanging(string value);
    partial void Onlsbh_lasttimeChanged();
    partial void Onlsbh_codeChanging(string value);
    partial void Onlsbh_codeChanged();
    #endregion
		
		public lsgl_lsbh()
		{
			OnCreated();
		}
		
		[Column(Storage="_lsbh_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int lsbh_id
		{
			get
			{
				return this._lsbh_id;
			}
			set
			{
				if ((this._lsbh_id != value))
				{
					this.Onlsbh_idChanging(value);
					this.SendPropertyChanging();
					this._lsbh_id = value;
					this.SendPropertyChanged("lsbh_id");
					this.Onlsbh_idChanged();
				}
			}
		}
		
		[Column(Storage="_lsbh_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lsbh_name
		{
			get
			{
				return this._lsbh_name;
			}
			set
			{
				if ((this._lsbh_name != value))
				{
					this.Onlsbh_nameChanging(value);
					this.SendPropertyChanging();
					this._lsbh_name = value;
					this.SendPropertyChanged("lsbh_name");
					this.Onlsbh_nameChanged();
				}
			}
		}
		
		[Column(Storage="_lsbh_beforetime", DbType="VarChar(50)")]
		public string lsbh_beforetime
		{
			get
			{
				return this._lsbh_beforetime;
			}
			set
			{
				if ((this._lsbh_beforetime != value))
				{
					this.Onlsbh_beforetimeChanging(value);
					this.SendPropertyChanging();
					this._lsbh_beforetime = value;
					this.SendPropertyChanged("lsbh_beforetime");
					this.Onlsbh_beforetimeChanged();
				}
			}
		}
		
		[Column(Storage="_lsbh_lasttime", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lsbh_lasttime
		{
			get
			{
				return this._lsbh_lasttime;
			}
			set
			{
				if ((this._lsbh_lasttime != value))
				{
					this.Onlsbh_lasttimeChanging(value);
					this.SendPropertyChanging();
					this._lsbh_lasttime = value;
					this.SendPropertyChanged("lsbh_lasttime");
					this.Onlsbh_lasttimeChanged();
				}
			}
		}
		
		[Column(Storage="_lsbh_code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lsbh_code
		{
			get
			{
				return this._lsbh_code;
			}
			set
			{
				if ((this._lsbh_code != value))
				{
					this.Onlsbh_codeChanging(value);
					this.SendPropertyChanging();
					this._lsbh_code = value;
					this.SendPropertyChanged("lsbh_code");
					this.Onlsbh_codeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
