#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4961
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="zsgl_solution")]
	public partial class UserDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertyhgl_users(yhgl_users instance);
    partial void Updateyhgl_users(yhgl_users instance);
    partial void Deleteyhgl_users(yhgl_users instance);
    #endregion
		
		public UserDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["zsgl_solutionConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<yhgl_users> yhgl_users
		{
			get
			{
				return this.GetTable<yhgl_users>();
			}
		}
	}
	
	[Table(Name="dbo.yhgl_users")]
	public partial class yhgl_users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_psw;
		
		private int _level_id;
		
		private string _user_name;
		
		private string _user_email;
		
		private string _user_bm;
		
		private string _user_mobile;
		
		private string _user_tel;
		
		private string _user_fax;
		
		private string _user_qy;
		
		private string _user_avatar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_pswChanging(string value);
    partial void Onuser_pswChanged();
    partial void Onlevel_idChanging(int value);
    partial void Onlevel_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_emailChanging(string value);
    partial void Onuser_emailChanged();
    partial void Onuser_bmChanging(string value);
    partial void Onuser_bmChanged();
    partial void Onuser_mobileChanging(string value);
    partial void Onuser_mobileChanged();
    partial void Onuser_telChanging(string value);
    partial void Onuser_telChanged();
    partial void Onuser_faxChanging(string value);
    partial void Onuser_faxChanged();
    partial void Onuser_qyChanging(string value);
    partial void Onuser_qyChanged();
    partial void Onuser_avatarChanging(string value);
    partial void Onuser_avatarChanged();
    #endregion
		
		public yhgl_users()
		{
			OnCreated();
		}
		
		[Column(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[Column(Storage="_user_psw", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_psw
		{
			get
			{
				return this._user_psw;
			}
			set
			{
				if ((this._user_psw != value))
				{
					this.Onuser_pswChanging(value);
					this.SendPropertyChanging();
					this._user_psw = value;
					this.SendPropertyChanged("user_psw");
					this.Onuser_pswChanged();
				}
			}
		}
		
		[Column(Storage="_level_id", DbType="Int NOT NULL")]
		public int level_id
		{
			get
			{
				return this._level_id;
			}
			set
			{
				if ((this._level_id != value))
				{
					this.Onlevel_idChanging(value);
					this.SendPropertyChanging();
					this._level_id = value;
					this.SendPropertyChanged("level_id");
					this.Onlevel_idChanged();
				}
			}
		}
		
		[Column(Storage="_user_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[Column(Storage="_user_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string user_email
		{
			get
			{
				return this._user_email;
			}
			set
			{
				if ((this._user_email != value))
				{
					this.Onuser_emailChanging(value);
					this.SendPropertyChanging();
					this._user_email = value;
					this.SendPropertyChanged("user_email");
					this.Onuser_emailChanged();
				}
			}
		}
		
		[Column(Storage="_user_bm", DbType="VarChar(100)")]
		public string user_bm
		{
			get
			{
				return this._user_bm;
			}
			set
			{
				if ((this._user_bm != value))
				{
					this.Onuser_bmChanging(value);
					this.SendPropertyChanging();
					this._user_bm = value;
					this.SendPropertyChanged("user_bm");
					this.Onuser_bmChanged();
				}
			}
		}
		
		[Column(Storage="_user_mobile", DbType="VarChar(20)")]
		public string user_mobile
		{
			get
			{
				return this._user_mobile;
			}
			set
			{
				if ((this._user_mobile != value))
				{
					this.Onuser_mobileChanging(value);
					this.SendPropertyChanging();
					this._user_mobile = value;
					this.SendPropertyChanged("user_mobile");
					this.Onuser_mobileChanged();
				}
			}
		}
		
		[Column(Storage="_user_tel", DbType="VarChar(20)")]
		public string user_tel
		{
			get
			{
				return this._user_tel;
			}
			set
			{
				if ((this._user_tel != value))
				{
					this.Onuser_telChanging(value);
					this.SendPropertyChanging();
					this._user_tel = value;
					this.SendPropertyChanged("user_tel");
					this.Onuser_telChanged();
				}
			}
		}
		
		[Column(Storage="_user_fax", DbType="VarChar(20)")]
		public string user_fax
		{
			get
			{
				return this._user_fax;
			}
			set
			{
				if ((this._user_fax != value))
				{
					this.Onuser_faxChanging(value);
					this.SendPropertyChanging();
					this._user_fax = value;
					this.SendPropertyChanged("user_fax");
					this.Onuser_faxChanged();
				}
			}
		}
		
		[Column(Storage="_user_qy", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string user_qy
		{
			get
			{
				return this._user_qy;
			}
			set
			{
				if ((this._user_qy != value))
				{
					this.Onuser_qyChanging(value);
					this.SendPropertyChanging();
					this._user_qy = value;
					this.SendPropertyChanged("user_qy");
					this.Onuser_qyChanged();
				}
			}
		}
		
		[Column(Storage="_user_avatar", DbType="VarChar(100)")]
		public string user_avatar
		{
			get
			{
				return this._user_avatar;
			}
			set
			{
				if ((this._user_avatar != value))
				{
					this.Onuser_avatarChanging(value);
					this.SendPropertyChanging();
					this._user_avatar = value;
					this.SendPropertyChanged("user_avatar");
					this.Onuser_avatarChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
