#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4959
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="zsgl_solution")]
	public partial class wjnrDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertwjgl_wjnrjs(wjgl_wjnrjs instance);
    partial void Updatewjgl_wjnrjs(wjgl_wjnrjs instance);
    partial void Deletewjgl_wjnrjs(wjgl_wjnrjs instance);
    #endregion
		
		public wjnrDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["zsgl_solutionConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public wjnrDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public wjnrDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public wjnrDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public wjnrDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<wjgl_wjnrjs> wjgl_wjnrjs
		{
			get
			{
				return this.GetTable<wjgl_wjnrjs>();
			}
		}
	}
	
	[Table(Name="dbo.wjgl_wjnrjs")]
	public partial class wjgl_wjnrjs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nr_id;
		
		private string _file_id;
		
		private string _file_nr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnr_idChanging(int value);
    partial void Onnr_idChanged();
    partial void Onfile_idChanging(string value);
    partial void Onfile_idChanged();
    partial void Onfile_nrChanging(string value);
    partial void Onfile_nrChanged();
    #endregion
		
		public wjgl_wjnrjs()
		{
			OnCreated();
		}
		
		[Column(Storage="_nr_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nr_id
		{
			get
			{
				return this._nr_id;
			}
			set
			{
				if ((this._nr_id != value))
				{
					this.Onnr_idChanging(value);
					this.SendPropertyChanging();
					this._nr_id = value;
					this.SendPropertyChanged("nr_id");
					this.Onnr_idChanged();
				}
			}
		}
		
		[Column(Storage="_file_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string file_id
		{
			get
			{
				return this._file_id;
			}
			set
			{
				if ((this._file_id != value))
				{
					this.Onfile_idChanging(value);
					this.SendPropertyChanging();
					this._file_id = value;
					this.SendPropertyChanged("file_id");
					this.Onfile_idChanged();
				}
			}
		}
		
		[Column(Storage="_file_nr", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string file_nr
		{
			get
			{
				return this._file_nr;
			}
			set
			{
				if ((this._file_nr != value))
				{
					this.Onfile_nrChanging(value);
					this.SendPropertyChanging();
					this._file_nr = value;
					this.SendPropertyChanged("file_nr");
					this.Onfile_nrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
